{{- if and .Values.credentials.create (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghes-multi-instance-github-app.credentialsSecretName" . }}
  labels:
    {{- include "ghes-multi-instance-github-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.credentials.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
