replicaCount: 1

image:
  repository: jfrog.hub.vwgroup.com/columbus-data-platform-docker-releases/github-app
  pullPolicy: IfNotPresent
  tag: "v1"

imagePullSecrets: 
  - name: vault-devhub-artifactory-pull-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "openshift-default"
  annotations: {}
  hosts:
    - host: dev.github.apps.columbus.apps.dev-intranet-02-wob.ocp.vwgroup.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

certificate:
  enabled: false
  name: ""
  secretName: ""
  annotations: {}
  labels: {}
  commonName: ""
  dnsNames: []
  duration: ""
  renewBefore: ""
  issuerRef:
    group: ""
    kind: ClusterIssuer
    name: ""
  privateKey:
    algorithm: ""
    encoding: ""
    rotationPolicy: ""
    size: null
  subject:
    countries: []
    organizations: []
  usages: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

nodeSelector: {}
tolerations: []
affinity: {}

app:
  logLevel: info
  instancesConfigPath: /app/config/instances.json
  extraEnv: []
  instances:
    - key: ghes1
      name: GHES 1
      baseUrl: https://vwg.ghe.com/
      appIdEnv: GHES1_APP_ID
      privateKeyEnv: GHES1_PRIVATE_KEY
      webhookSecretEnv: GHES1_WEBHOOK_SECRET
    - key: ghes2
      name: GHES 2
      baseUrl: https://git.hub.vwgroup.com/
      appIdEnv: GHES2_APP_ID
      privateKeyEnv: GHES2_PRIVATE_KEY
      webhookSecretEnv: GHES2_WEBHOOK_SECRET

credentials:
  existingSecret: ""
  create: true
  data:
    GHES1_APP_ID: ""
    GHES1_PRIVATE_KEY: ""
    GHES1_WEBHOOK_SECRET: ""
    GHES2_APP_ID: ""
    GHES2_PRIVATE_KEY: ""
    GHES2_WEBHOOK_SECRET: ""
